apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.nfs_provider.storage_class_name }}
  #annotations:
  #  storageclass.kubernetes.io/is-default-class: true
provisioner: fuseim.pri/ssd1 # or choose another name, must match deployment's env PROVISIONER_NAME'
