apiVersion: v1
kind: Service
metadata:
  name: rest
spec:
  ports:
  - port: 8082
  selector:
    app: kafka-rest
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-rest
    spec:
      containers:
      - name: kafka-rest
        image: confluentinc/cp-kafka-rest:5.1.1
        env:
        - name: KAFKA_REST_LISTENERS
          value: http://0.0.0.0:8082/
        - name: KAFKA_REST_HOST_NAME
          value: kafka-rest
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: PLAINTEXT://kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value: zk-cs.kafka.svc.cluster.local:2181
        ports:
        - containerPort: 8082

