---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: gateway
  namespace: openfaas
  annotations:
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: openfaas-gateway.internal.dom.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: gateway
          servicePort: 8080
status:
  loadBalancer: {}
